version: "3.9"
services:
  pg: 
    image: postgres:14.2
    restart: "always"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=prisma
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "./.db/data:/var/lib/postgresql/data"
      - "./.db/init:/docker-entrypoint-initdb.d"
volumes: 
  db:
    driver: local