version: "3.9"
services:
  pg: 
    image: postgres:14.5
    restart: "always"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=prisma
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./.pg:/var/lib/postgresql/data:rw

volumes:
  pg:
    driver: local